OMAP: GPIO: Fix compilation error due to set_irq_type
Fix the following compilation error
gpio/test_code/utils/gpio_mods/gpio_test.c:118: error: implicit
declaration of function 'set_irq_type'

Signed-off-by: Charulatha V <charu@ti.com>