TestSuites: bc: Add missing string.h include
This fixes all these warnings:

../../lib/number.c: In function 'bc_new_num':
../../lib/number.c:76: warning: implicit declaration of function 'memset'
../../lib/number.c:76: warning: incompatible implicit declaration of built-in function 'memset'
../../lib/number.c: In function 'bc_sub':
../../lib/number.c:558: warning: incompatible implicit declaration of built-in function 'memset'
../../lib/number.c: In function 'bc_add':
../../lib/number.c:607: warning: incompatible implicit declaration of built-in function 'memset'
../../lib/number.c: In function '_one_mult':
../../lib/number.c:901: warning: incompatible implicit declaration of built-in function 'memset'
../../lib/number.c:905: warning: implicit declaration of function 'memcpy'
../../lib/number.c:905: warning: incompatible implicit declaration of built-in function 'memcpy'
../../lib/number.c: In function 'bc_divide':
../../lib/number.c:956: warning: incompatible implicit declaration of built-in function 'memset'
../../lib/number.c:957: warning: incompatible implicit declaration of built-in function 'memcpy'
../../lib/number.c:978: warning: incompatible implicit declaration of built-in function 'memset'
../../lib/number.c:979: warning: incompatible implicit declaration of built-in function 'memcpy'
../../lib/number.c: In function 'bc_out_long':
../../lib/number.c:1442: warning: implicit declaration of function 'strlen'
../../lib/number.c:1442: warning: incompatible implicit declaration of built-in function 'strlen'

Signed-off-by: Sergio Aguirre <saaguirre@ti.com>